### ISSUE TITLE
Kernel updates marked manual

### ISSUE THREAD

**Issue by private-lock** [PackageKit/PackageKit#450] opened 2021-01-20 20:48 UTC
Hi

Reported this already [to launchpad](https://bugs.launchpad.net/ubuntu/+source/unattended-upgrades/+bug/1675079/comments/37) and [KDE](https://bugs.kde.org/show_bug.cgi?id=430296).

Applying kernel-updates through apt command-line, they are marked as "automatic" and fit for removal by a subsequent call of "apt autoremove" later, once more kernels supersede it. (WORKS AS EXPECTED)

But when I apply any new version of the kernel through the KDE/Plasma update notification, then it gets marked as manual (BUG) ... even if I clean-out the manual status before - this is what it looks right before and after applying updates:

root@Meerschweinchen:/home/holger# apt-mark showmanual 'linux-.*'
linux-base
linux-generic
root@Meerschweinchen:/home/holger# apt-mark showmanual 'linux-.*'
linux-base
linux-generic
linux-headers-5.4.0-64
linux-headers-5.4.0-64-generic
linux-image-5.4.0-64-generic
linux-modules-5.4.0-64-generic
linux-modules-extra-5.4.0-64-generic

Versions:
root@Meerschweinchen:/home/holger# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
root@Meerschweinchen:/home/holger# uname -a
Linux Meerschweinchen 5.4.0-62-generic #70-Ubuntu SMP Tue Jan 12 12:45:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
root@Meerschweinchen:/home/holger# apt list packagekit discover
Auflistung... Fertig
discover/focal 2.1.2-8 amd64
packagekit/focal-updates,focal-security,now 1.1.13-2ubuntu1.1 amd64  [installiert]

**Comment by mauromol** [comment] 2021-01-29 09:53
I have the same problem in Kubuntu 20.04, my boot partition got full and I discovered this problem. Kernel updates installed through the Discover UI (through the "update all" button) are marked as manually installed, hence unattended-upgrades/apt autoremove cannot automatically delete old kernerls like they should, as documented at: https://help.ubuntu.com/community/RemoveOldKernels

**Comment by hklene** [comment] 2021-02-09 19:36
Meanwhile I switched to Kubuntu 20.10 - but the bug persists. I made a video for you of an update.

Latest versions:
root@Meerschweinchen:/home/holger# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.10
Release:        20.10
Codename:       groovy
root@Meerschweinchen:/home/holger# uname -a
Linux Meerschweinchen 5.8.0-41-generic #46-Ubuntu SMP Mon Jan 18 16:48:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
root@Meerschweinchen:/home/holger# apt list packagekit discover
Auflistung… Fertig
discover/groovy 2.1.2-8 amd64
packagekit/groovy,now 1.1.13-2ubuntu2 amd64  [installiert]


https://user-images.githubusercontent.com/7427503/107418076-859c5600-6b16-11eb-8eba-63842ca7909b.mp4

**Comment by eeickmeyer** [comment] 2021-09-02 21:54
@hughsie Why did you put a thumbs-down on my comment?

**Comment by hughsie** [comment] 2021-09-03 11:01
> Why did you put a thumbs-down on my comment

I didn't like your attitude to be honest. _This needs to be fixed_ comes across as hostile, and then you said that you've developed a workaround rather than finding the root cause (another thumbs-down) and then that you have [presumably paying] customers and expecting people working for free to fix the issue (another thumbs-down).

**Comment by eeickmeyer** [comment] 2021-09-03 14:43
@hughsie I am terribly sorry. I did not mean to come across as hostile. That was not my intention. Honestly, if there's anything I can do to help, let me know.

We would rather not have developed the workaround (a bash script), but time was of the essence. I'm not familiar enough with the code to know where to start here, to be honest, but as I said, I'd rather help than be perceived as hostile.

Yes, we have paying customers, but it's not ongoing and it's for a computer.

Again, I am terribly sorry and hope not to come across that way in this message or in the future. I'm a really nice guy, ask anyone. :)

**Comment by mmikowski** [comment] 2021-09-03 21:30
@hughsie @eeickmeyer

I hope this response helps clarify the purpose and severity of this issue.

> "You've developed a workaround rather than finding the root cause"

Good sysadmins know to triage first and assess later. That's what we did. This triage solution was critical because users were bricking systems with overfull boot directories. That appears to have been a good decision, because it took days of research to determine the root cause, and nothing has been done about this in PackageKit for 6 months.

> "And then that you have [presumably paying] customers ... and expecting people working for free to fix the issue"

The customers mentioned are already covered thanks to the triage work discussed above. It appears everyone else running PackageKit + Apt are prone to encounter this issue, especially those who use full disk encryption due to the limited boot partition size.

Here are some more bugs reports: [Reddit](https://www.reddit.com/r/kde/comments/em79hy/kde_desktop_wont_boot_if_no_disk_space_available/), [Launchpad01](https://bugs.launchpad.net/ubuntu/+source/plasma-discover/+bug/1914932), [Launchpad02](https://bugs.launchpad.net/ubuntu/+source/apt/+bug/1914278), [KDE Bug](https://bugs.kde.org/show_bug.cgi?id=432513).  If you need more, search for 'PackageKit /boot partition full'

**Comment by apachelogger** [comment] 2021-09-06 14:04
- Here's a workaround we have rolling out in neon https://invent.kde.org/neon/neon/settings/-/commit/abda90d8fac48cf30161a27859d212c5f70e231e
- This bug affects every package that is implicitly pulled in by any update, not just kernels

From staring at the code a bit I'm fairly confident what happens is that the runTransactions is losing the state (or rather it never knew). GetUpdates returns a list of all packages that will be mutated (newly pulled in packages are marked for install) so then what happens is that the client feeds that list back into UpdatePackages. Meanwhile we'v lost track of what was auto and what was not and have no reasonable way to guess again inside runTransaction/tryToInstall. The package list is then simply fed to tryToInstall causing new packages to get installed manually and thus lack the auto flag. What we'd need to do is somehow know that they should be auto and only manually tryToInstall them if nothing pulls them in via auto mode.

Assuming my reading of the code is correct we'd either need a way to shove the auto state into the package_id so the client can give the information back to us. Do we have a way to do that? I'm guessing not since we'd have to encode that in the package_id syntax somehow.

Or, less ideally, we could resolve a complete DistUpgrade again (same as we did in GetUpdates) to get a list of expected auto packages so we can then tell which packages the client gave as input should indeed be auto.

In either event the runTransaction logic probably needs adjustments to first tryToInstall() all ids that require **actual** update and then further tryToInstall() the additional ids that required installation BUT only if they hadn't already been marked implicitly by the actual updates. i.e. if an upgrade-candidate auto-marks an install-candidate for installation, the latter oughtn't get marked for manual installation again - thus preserving auto state.

**Comment by ximion** [comment] 2021-09-06 21:14
@apachelogger 
> Assuming my reading of the code is correct

I think that's the case :-)

> we'd either need a way to shove the auto state into the package_id so the client can give the information back to us. Do we have a way to do that? I'm guessing not since we'd have to encode that in the package_id syntax somehow.

That's what the "data" part (last bit of a package-ID) is for, so that can be done, would be extremely ugly though, as "data" is already overloaded with lots of other meanings as well.

> Or, less ideally, we could resolve a complete DistUpgrade again (same as we did in GetUpdates) to get a list of expected auto packages so we can then tell which packages the client gave as input should indeed be auto.

Couldn't we just ask the APT cache for the manual/auto state of the current package again and then keep that state? That should be pretty quick and should solve this issue too, and we would avoid a whole resolve run.

> In either event the runTransaction logic probably needs adjustments to first tryToInstall() all ids that require actual update and then further tryToInstall() the additional ids that required installation BUT only if they hadn't already been marked implicitly by the actual updates. i.e. if an upgrade-candidate auto-marks an install-candidate for installation, the latter oughtn't get marked for manual installation again - thus preserving auto state.

Exactly this. I think APTcc's `runTransaction()` is wrong in merking "update" packages and "install" packages together. We want to first run the updates, preserving their auto/manual state, and then run the pure ones marked as installation, marking those packages as "manual".

**Comment by apachelogger** [comment] 2021-09-07 10:49
> Couldn't we just ask the APT cache for the manual/auto state of the current package again and then keep that state? That should be pretty quick and should solve this issue too, and we would avoid a whole resolve run.

Worth trying but I don't have high hopes. Chances are the package is not auto when not-installed. This actually plays into your other thought though...

> Exactly this. I think APTcc's runTransaction() is wrong in merking "update" packages and "install" packages together. We want to first run the updates, preserving their auto/manual state, and then run the pure ones marked as installation, marking those packages as "manual".

What happens already is that iff the package was in auto state that would get preserved (that's what the fromUser magic in  `tryToInstall()` does). By extension I suppose we can assume that not-installed packages don't have auto set, otherwise the existing code would already preserve it. The thing to note is the current `Operation` list for install is empty because `backend_manage_packages_thread` fills only the updates list because it is run with update role. What I was proposing is changing that so we actually have a list of packages that would need "new" installation as opposed to consider them all updates.

Instead of calculating the entire upgrade we could simply check the existing state of the package for that. The disadvantage compared to a complete calculation is that we cannot tell if the package would be auto as a result of the upgrade. e.g. `pkcon update foo bar` with only foo installed would still install bar but set it auto, which arguably makes no sense to the user. But then that can still be partially true with a distupgrade calculation. It's part of why I think passing the auto state in the id may be the best approach to cover all cases.

- `pkcon update` -> bar has auto hint in package_id, install it as such
- `pkcon update foo` -> bar is not mentioned -> implicit auto install
- `pkcon update foo bar` -> explicit manual install of bar (could also opt to fail TBH, I can't see any documentation about update on a not-installed package having any expectation to succeed)

We could of course also opt to consider `update foo bar` with bar not installed undefined behavior seeing as I can't find documentation on it and then consider all newly installed packages in the updates list auto. Certainly makes for both the least amount of extra code.

**Comment by mauromol** [comment] 2021-09-07 13:24
Sorry if I'm going to say some nonsense, but from a user point of view, if `package1` from a certain point in time starts to require `package2`, when I do:
`apt install package1 package2`
`package2` is marked as manually installed, while, if I do just:
`apt install package1`
and package2 gets transitively installed due to `package1` update, then `package2` is marked as automatically installed.
When I update my system I sometimes see that changes in packaging cause new packages to be installed, but I expect them to be still marked as automatically installed, because they are brought in transitively and not installed due to an explicit request.
With kernel updates perhaps something similar occurs, because the system updates generic packages (like `linux-image-generic`) and these bring in new packages over time (like `linux-image-5.4.0-81-generic` currently) as new kernel versions are released.

If this comment is completely non-relevant, please ignore :-)

**Comment by ximion** [comment] 2021-10-06 02:32
@apachelogger I agree with your analysis. A package-ID is `name;version;arch;data` with the `data` block almost always being used as `origin`, e.g. `debian-unstable-main`. How *exactly* `data` is handled can be changed in PackageKit's backends though, I don't think PK itself will make any assumptions about `data` (at least it certainly didn't last time I was deep-diving into it).

I always disliked misusing `data` for `origin`, so we could change it, for example like this: `hello;1.0;amd64;origin=debian-unstable-main` - if we want to pass a mode along, we could do  `hello;1.0;amd64;origin=debian-unstable-main&mode=auto`. This means we would make `&` a special character, but origin strings shouldn't use that anyway, and `mode` would be a defined enum. This change *should* be backwards-compatible, unless something external is parsing the data part of the ID (which it really, really shouldn't do).
Any alternative would mean we have to expand the package-ID itself by adding more parts, which is certainly doable, but I have no idea how much breakage that would cause. Given that it hasn't changed in a decade, probably a lot ^^

**Comment by Bleuzen** [comment] 2022-01-01 16:41
> We would rather not have developed the workaround (a bash script),

@eeickmeyer can you share your script/workaround?

**Comment by mmikowski** [comment] 2022-01-29 00:21
Hey @Bleuzen, sorry this took so long, but I was just asked about this today and here is the script.  I hope you find that useful, and if you'd like to collaborate on making it better, just let me know. You can see more details at [here](https://kfocus.org/wf/tools.html#kclean). Notice, this is *very* Ubuntu specific as it depends on their package naming conventions.

[kfocus-kernel-cleaner.txt](https://github.com/PackageKit/PackageKit/files/7962566/kfocus-kernel-cleaner.txt)

I had to merge and simplify routines from common libraries to get this into a single script. In particular, I did not port over the GUI interface from library due to the added complexity (it normally runs in either CLI or GUI mode).

- This has been used regularly by many, many users with rarely an issue.
- The most common issue is when a user ignores regular cleaning. Especially on encrypted systems, this can completely fill the /boot partition and break packages.
- The logic does not consider any aspect of apt-mark, but instead calculates the kernel packages that should be retained
- I added a section to repair packages and rebuild dkms + initramfs. Consider this experimental.
- The script passes shellcheck and IntelliJ BashSupportPro inspections.

Heuristics: These 'blessed' kernels are always kept by this script.

1. The current running kernel
2. The latest oem-20.04d-kfocus kernel
3. The latest lowlatency-hwe-20.04 kernel
4. The latest generic-hwe-20.04 kernel 

If the total number of version is less than `_tgt_kvers_min_count`, other kernels will be retained to keep the minimum count, with higher natural version numbers given preference. A kernel check is triggered if the number of kernels exceeds a maximum (`_tgt_kvers_max_count`) or disk space in the /boot partition is exceeded (`_max_pct_int`) and it is a mount point

In the future, we should like to allow the user to set their preferred 'blessed' kernels instead hard-coding this into the script.

**Comment by mmikowski** [comment] 2022-02-01 04:36
@Bleuzen @eeickmeyer I updated the kernel cleaner post above with the latest version of the script which I ran through our regression mocks to iron out edge cases.

@ximion thanks for tackling the primary issues here.

**Comment by Bleuzen** [comment] 2022-02-01 21:43
@mmikowski  thanks a lot for this :)
Haven't tried it yet.

Also here is an alternative idea that I'm using currently.

In: `/etc/cron.weekly/mark-kernels-auto-installed`

```
#!/bin/sh
apt-mark auto $(apt-mark showmanual | grep -E "^linux-([[:alpha:]]+-)+[[:digit:].]+-[^-]+(|-.+)$")
```
And after creating this file, set permissions: 
`chmod 755 /etc/cron.weekly/mark-kernels-auto-installed`

This only handles setting the kernels to auto installed. Not sure yet if apt automatically removes them after updates. If not, you could add `apt autoremove -y` to the end of that script to fully automate it.

**Comment by mmikowski** [comment] 2022-02-01 21:55
@Bleuzen I really like that. Certainly far simpler and more comprehensive. Then we can let unattended-upgrades handle the rest. I would like to run it right after any apt upgrade using /etc/apt/apt.conf.d/.  I'll give it a go and report back!

**Comment by mmikowski** [comment] 2022-02-01 23:10
@Bleuzen @eeickmeyer We created a hook for post installs and initial testing looks good. Here's what we have:

**/etc/apt/apt.conf.d/000-kfocus-mark-kernels**
```
DPkg::Post-Invoke {"if [ -x /usr/bin/kfocus-mark-kernels ]; then kfocus-mark-kernels; fi";};
```

**/usr/bin/kfocus-mark-kernels**
```
#!/bin/bash

_argStr="$*";
_debugFile="/tmp/DEBUG-automark";

read -r -d '' -a _manualList < <( apt-mark showmanual \
  | grep -E '^linux-([[:alpha:]]+-)+[[:digit:].]+-[^-]+(|-.+)$'
);

{ date
  cat <<_EOF
_argStr     = >${_argStr}<
_manualList = >${_manualList[*]}<
_EOF
  apt-mark auto "${_manualList[@]}";
} >> "${_debugFile}";
```

See `/tmp/DEBUG-automark` for debugging. We are currently running this through some tests and will report back.  I hope you find this useful.

**Comment by mmikowski** [comment] 2022-02-02 19:08
@Bleuzen @eeickmeyer I updated the [comment above](#issuecomment-1027377745) on my our findings. While marking kernel packages as auto works great, unattended-upgrades has yet to clean any out. Neither does `apt autoremove`. I currently have a hunch as to what's going on.

@Bleuzen Is there a better place to have this discussion? While it is tangential to the issue, we might be better discussing elsewhere. We may be able to host a separate shared git repo or similar.

**Comment by Bleuzen** [comment] 2022-02-02 22:25
@mmikowski  I just created a repo and uploaded what we have so far.
Also there is a new issue for discussion:
https://github.com/Bleuzen/ubuntu-kernel-autoremove/issues/1

**Closed** 2022-02-04 21:50 UTC
Labels: Backend: aptcc (Debian GNU/Linux)

**Comment by ximion** [comment] 2022-02-04 21:52
Please test if the updated PK version works for you!
(and maybe we can get a release soon, to make testing easier)
I've been using this change for more than a week now and noticed no issues so far.

**Comment by mmikowski** [comment] 2022-02-08 23:56
@ximion Thank you. We will test on Kubuntu 22.04 (Jammy).  Does the following procedure sound good to you?

* Run two VMs with Jammy. One will have the package kit upgraded to the latest PK.
* On both VMs, install the same kernels and other packages using Discover (which uses PackageKit).
* Compare the auto/manual marks on installed packages

**Comment by ximion** [comment] 2022-02-09 04:52
Yes, that makes sense - just diff'ing `apt-mark showauto` & Co. would make sense, and your scenario is a bit more complex thanthe one I tested (with downgrading and upgrading packages a bunch of times)

**Comment by mmikowski** [comment] 2022-02-09 21:49
@ximion Thanks for the feedback. We'll proceed with this testing scenario then.

**Comment by Bleuzen** [comment] 2022-02-10 22:16
@ximion  Just wanted to say thank you for working on this :)
Hope this will finally work in Ubuntu 22.04.



> (and maybe we can get a release soon, to make testing easier)

yeah this would help.

Also, speaking about a release: if this should land in Ubuntu 22.04, I hope it won't be too late as "Debian Import Freeze" is on February 24.

**Comment by ximion** [comment] 2022-02-10 23:53
> guess it won't but does packagekit support autoremoving kernels on upgrade or will manually running apt autoremove still be necessary?

It should auto-remove kernels, I added support for that to PK a while back. But this hasn't been properly tested yet (due to this bug still existing back then).

**Comment by mmikowski** [comment] 2022-02-14 04:01
Hi @ximion:

I tested with both the patched packagekit and the default packagekit in Jammy today as discussed above. The auto and manual marks look as expected. [2022-02-13-PkTest.zip](https://github.com/PackageKit/PackageKit/files/8057744/2022-02-13-PkTest.zip). I hope this is helpful.

I'll keep the patched version installed and keep an eye out for how well the kernels get cleaned out during upgrades.

Cheers, Mike

**Comment by ximion** [comment] 2022-02-14 05:08
@mmikowski Thank you! Possibly a fairly dumb question, but: In the procedure*.md files, it shows no kernel to be included in the upgrade, and if I do `diff -u pktest-patched-start-manual-marks.txt pktest-patched-step02-manual-marks.txt` I get
```diff
@@ -9,6 +9,7 @@
 efibootmgr
 findutils
 fonts-indic
+gimp
 git
 grep
 grub-common
@@ -24,6 +25,8 @@
 hyphen-en-us
 init
 inkscape
+kdiff3
+krita
 kubuntu-desktop
 kubuntu-wallpapers
 language-pack-en
@@ -38,14 +41,19 @@
 libplacebo192
 libreoffice-help-en-us
 linux-generic
+linux-generic-hwe-20.04
+linux-oem-20.04
 login
 lvm2
+meld
 mokutil
 mythes-en-us
 ncurses-base
 ncurses-bin
 os-prober
 ppa-purge
+rsync
+shellcheck
 shim-signed
 thin-provisioning-tools
 thunderbird-locale-en
@@ -55,4 +63,5 @@
 vim-nox
 wamerican
 wbritish
+webcamoid
 xdg-desktop-portal-gtk
```
which is actually an expected result as those packages were indeed installed manually. The updates that were applied keep their states as they should, but they also should have done that before (so my changes at least didn't regress anything ^^).
Am I missing something here?

**Comment by mmikowski** [comment] 2022-02-19 04:40
@ximion on a related issue ... 

You mentioned that packagekit will now clean up out-of-date kernels. I believe it is best practice to keep the last two versions of any particular kernel flavor, and of course any running kernel version. For example:

```
llinux-oem-20.04d 5.14.0.1022
llinux-oem-20.04d 5.14.0.1018

linux-generic-hwe-20.04 5.13.0.30
linux-generic-hwe-20.04 5.13.0.28

linux-lowlatency-hwe-20.04 5.13.0.30
linux-lowlatency-hwe-20.04 5.13.0.28
```

With this update, are you relying on auto-clean, or unattended-upgrades, or something else to clean up the old packages?

We have installed unattended-upgrades, however, we have found that the algorithm in 20.04 does not support support the two-version-per-kernel-meta rule but instead just tries to keep the last 3 or 4 kernels installed. I feel it would be good to update this algorithm. Here are some steps in that direction:

- File and comment on upstream bugs to address the too-small /boot partition on FDE systems (here)[https://bugs.launchpad.net/ubuntu/+source/ubiquity/+bug/1960089] and (here)[https://bugs.launchpad.net/ubuntu/+source/partman-auto/+bug/1959971]
- Create [kernel cleaner tool](https://kfocus.org/wf/tools#kclean)
- Collaborate with @Bleuzen to refine removal criteria in (this project][https://github.com/Bleuzen/ubuntu-kernel-autoremove]

We could either create a "blessed" list of top-level meta packages to keep (probably preferred, and what we do today), or ask the user to specify which to keep (I like this less, but it might be needed in some cases).

Even if you can't help with this, I am curious if you think this is worth pursuing.

**Comment by ximion** [comment] 2022-02-19 04:52
There is no need for any complexity here. If this works as it should (and the feature hasn't been disabled somehow or PackageKit compromised it by marking everything as manual), APT will already auto-remove all unused kernels and keep the running one and the latest one.
See https://sources.debian.org/src/apt/2.3.15/apt-pkg/algorithms.cc/#L1460 and also `APT::Get::AutomaticRemove::Kernels`.

**Comment by mmikowski** [comment] 2022-02-19 05:15
@ximion Thank you for the advice and references. I don't think I've every seen this work correctly, as I've used KDE (and thus packagekit) since switching to Ubuntu around 2004 and only started using FDE around 5 years ago. It looks like this is used in `/etc/apt/apt.conf.d/01autoremove-kernels`. This doesn't support the two-version-per-meta as suggested above, but perhaps that isn't as important. I'll see how it goes with the updated packagekit and trying to run multiple kernels.  Thanks again!

**Comment by julian-klode** [comment] 2022-02-23 17:39
@mmikowski This is an Ubuntu policy question, we decided that keeping multiple kernels per flavor would cause overflow of /boot and rejected the idea. It's not your place to override this decision. If you want that changed, bring your proposal to ubuntu-devel and see if it gets consensus and management buy-in.

**Comment by mmikowski** [comment] 2022-02-23 18:52
@julian-klode this was simply a suggestion of good practice. I'm already discussing the related /boot size issue directly and on ubuntu-devel. I agree, let's take the discussion there.
