### ISSUE TITLE
pk-offline-update killed by systemd after 10 minutes, leaving system in a broken state

### ISSUE THREAD

**Issue by Yvan-Masson** [PackageKit/PackageKit#590] opened 2022-12-23 22:28 UTC
Hi,

I first asked on debian-user@lists.debian.org but could not get an answer, so I try here. Please apologize if it is not the right place.

I am using Debian testing with KDE. I had a *lot* of updates that I tried to apply offline (initiated from Discover). However, offline update stopped before all packages where updated (at around 50%) and computer rebooted with packages in a broken state. I had to manually fix half installed packages with command line.

When I look journalctl, I see beginning of the update process:
```
17:44:41 pk-offline-update[742]: sent mode to plymouth 'updates'
```
And exactly ten minutes later it stops brutally:
```
17:54:39 pk-offline-update[742]: package preparing        packagekit-tools-1.2.6-1.amd64 (debian-testing-main)
17:54:39 pk-offline-update[742]: package decompressing        packagekit-tools-1.2.6-1.amd64 (debian-testing-main)
17:54:39 pk-offline-update[742]: package finished        packagekit-tools-1.2.6-1.amd64 (debian-testing-main)
17:54:39 pk-offline-update[742]: package installing        packagekit-tools-1.2.6-1.amd64 (debian-testing-main)
17:54:39 pk-offline-update[742]: package finished        packagekit-tools-1.2.6-1.amd64 (debian-testing-main)
17:54:39 pk-offline-update[742]: package preparing        packagekit-1.2.6-1.amd64 (debian-testing-main)
17:54:40 pk-offline-update[742]: package decompressing        packagekit-1.2.6-1.amd64 (debian-testing-main)
17:54:40 systemd[1]: packagekit-offline-update.service: Main process exited, code=killed, status=15/TERM
17:54:40 systemd[1]: packagekit-offline-update.service: Failed with result 'signal'.
```
It could be because packagekit tried to update itself, but then it should crash, not be killed by systemd. So I suppose it is a "timeout" issue, which could come from a systemd configuration or systemd unit, but could not find where. I found the default value `RebootWatchdogSec=10min` in `/etc/systemd/system.conf`, but after reading the manpage I don't think it matches my issue.

Do not hesitate to ask if you need more information, or if I should report this elsewhere.

packagekit before upgrade: 1.2.5-3+b1
packagekit after upgrade: 1.2.6-1
systemd before upgrade: 252.1-1
systemd after upgrade: 252.2-2

Regards,
Yvan

**Comment by hughsie** [comment] 2022-12-29 14:56
@ximion any ideas?

**Comment by Yvan-Masson** [comment] 2022-12-30 19:17
I have managed to reproduce the issue:
- install a Debian stable (Bullseye) VM with KDE desktop (but again I suppose it can be any DE)
- change APT sources to target current testing (Bookworm)
- run the following commands (yes I ran first two commands twice because first time `dbus-send` exited with an error):

```
pkcon update --only-download
dbus-send --system --type=method_call --print-reply \
  --dest=org.freedesktop.PackageKit \
  /org/freedesktop/PackageKit \
  org.freedesktop.PackageKit.Offline.Trigger \
  string:power-off
pkcon update --only-download
dbus-send --system --type=method_call --print-reply \
  --dest=org.freedesktop.PackageKit \
  /org/freedesktop/PackageKit \
  org.freedesktop.PackageKit.Offline.Trigger \
  string:power-off
sudo systemctl reboot
```

System reboots and again, update stops before the end. But after around 22 minutes. In fact, it stops exactly at the same step: just after decompressing `packagekit` package. In both cases I could confirm this by looking in `/var/log/apt/term.log`.

So this is not a timeout issue but rather a PackageKit backend or a Debian packaging issue.

**Comment by ximion** [comment] 2023-01-03 18:00
I'm pretty sure I know what the issue is. Give me a bit of time to address it. Also, thanks for the excellent bug report!

**Comment by ximion** [comment] 2023-01-04 04:06
jikes! Looks like it was indeed what I thought it was and this issue flew under the radar for a really long time... It's fixed now, and I will upload a fixed version to Debian soon. No need to report a bug against Debian, because one already exist (but I didn't recognize its severity until now).
Cheers,
    Matthias

Resolved via: https://salsa.debian.org/pkgutopia-team/packagekit/-/commit/e232878acbf9debc128ff28b2234df4b9b8a3965

**Closed by ximion** 2023-01-04 04:06 UTC
Labels: Backend: apt (Debian GNU/Linux)

**Comment by Yvan-Masson** [comment] 2023-01-04 08:37
Thanks @ximion! Glad that the information I gave was useful.
