### ISSUE TITLE
Two entries listed for each updated package in /var/lib/PackageKit/offline-update-competed

### ISSUE THREAD

**Issue by sidt4** [PackageKit/PackageKit#645] opened 2023-07-21 09:03 UTC
From: https://gitlab.gnome.org/GNOME/gnome-software/-/issues/2249#note_1796310

This happens on debian / apt. Not sure about other backends.

I simulated an offline update for a single package.

In `pk_offline_auth_set_results` ( `pk-offline-private.c` ), in the below code

```c
	/* save packages if any set */
	packages = pk_results_get_package_array (results);
	if (packages->len > 0) {
		g_autoptr(GString) string = NULL;
		string = g_string_new ("");
		for (i = 0; i < packages->len; i++) {
			package = g_ptr_array_index (packages, i);
			switch (pk_package_get_info (package)) {
			case PK_INFO_ENUM_UPDATING:
			case PK_INFO_ENUM_INSTALLING:
				g_string_append_printf (string, "%s,",
							pk_package_get_id (package));
				break;
			default:
				break;
			}
		}
		if (string->len > 0)
			g_string_set_size (string, string->len - 1);
		g_key_file_set_string (key_file,
				       PK_OFFLINE_RESULTS_GROUP,
				       "Packages",
				       string->str);
	}
```

There are 5 entries in `packages` all for the single package ( say, X ). The following were the `info` ( probably `action` ? ) for the 5 entries:

1. `PK_INFO_ENUM_PREPARING` - package X
1. `PK_INFO_ENUM_DECOMPRESSING` - package X
1. `PK_INFO_ENUM_INSTALLING` - package X
1. `PK_INFO_ENUM_PREPARING` - package X
1. `PK_INFO_ENUM_INSTALLING` - package X

So, there are 2 entries written to `/var/lib/PackageKit/offline-update-competed`

**Comment by sidt4** [comment] 2023-07-21 15:47
This was on latest debian unstable with `packagekit-1.2.6-5`.

**Comment by sidt4** [comment] 2023-08-11 19:40
This issue doesn't appear in `dnf` backend ( Tested on `PackageKit-1.2.6-6.fc38.x86_64` )

**Comment by mcrha** [comment] 2023-08-24 07:32
This is a duplicate of https://github.com/PackageKit/PackageKit/issues/284

**Closed** 2023-11-08 20:09 UTC

**Comment by Bushido1** [comment] 2024-01-19 11:30
Hello,

I am experiencing this issue in Linux Ubuntu 22.04 LTS with gnome-software 41.5.
![image](https://github.com/PackageKit/PackageKit/assets/11409601/bf4d5e48-6c05-4a61-9d71-40c7174be314)

**Comment by mcrha** [comment] 2024-01-22 10:36
gnome-software version does not matter, this is PackageKit project, thus what matters is PackageKit version instead. According to the referenced commit, the fix landed for PackageKit 1.2.8 .

**Comment by Bushido1** [comment] 2024-01-22 13:38
> gnome-software version does not matter, this is PackageKit project, thus what matters is PackageKit version instead. According to the referenced commit, the fix landed for PackageKit 1.2.8 .

How to check which PackageKit I am using?

**Comment by mcrha** [comment] 2024-01-22 16:07
It's a question for your distro or its forum or what they use. Nonetheless, the below command answers the question. I included also the answer from one test machine (I do not use Ubuntu), where the important bit is that the package is marked as "installed".

```
$ apt list packagekit
Listing... Done
packagekit/mantic,now 1.2.7-1 amd64 [installed,automatic]
```

**Comment by Bushido1** [comment] 2024-01-22 20:39
> It's a question for your distro or its forum or what they use. Nonetheless, the below command answers the question. I included also the answer from one test machine (I do not use Ubuntu), where the important bit is that the package is marked as "installed".
> 
> ```
> $ apt list packagekit
> Listing... Done
> packagekit/mantic,now 1.2.7-1 amd64 [installed,automatic]
> ```

I got the following answer:
`packagekit/jammy,now 1.2.5-2ubuntu2 amd64 [installed]
`
Ubuntu has not offered any updates, thus I must update it manually? If so, is my long term supported Ubuntu turning into a frankensystem?

**Comment by mcrha** [comment] 2024-01-23 09:54
These are questions for your distribution maintainers, really, nobody here can answer it. Long Term Support distros have their own rules when they update software and which. You can ask them to get a newer PackageKit and it'll be up to them to decide whether it's worth it or not. Or they can backport only the patch.

**Comment by Bushido1** [comment] 2024-09-10 08:28
> These are questions for your distribution maintainers, really, nobody here can answer it. Long Term Support distros have their own rules when they update software and which. You can ask them to get a newer PackageKit and it'll be up to them to decide whether it's worth it or not. Or they can backport only the patch.

I am still experiencing this in Ubuntu 24.04 LTS even after upgrade from 22.04 LTS.

**Comment by sidt4** [comment] 2024-09-10 10:52
@Bushido1: Please don't update the same issue report in multiple places.
