### ISSUE TITLE
PackageKit service fails with a core-dump due to unsupported directive HookDir in pacman.conf.

### ISSUE THREAD

**Issue by ericonr** [PackageKit/PackageKit#342] opened 2019-10-04 22:18 UTC
**PackageKit version**

> 1.1.12-1

**Used distribution**

 > Manjaro Stable

**Expected behaviour you didn't see**

 > PackageKit service should be able to parse a standard pacman.conf file without core dumping. Being able to deal with unknown directives could be the best solution for parameters that are not relevant to PackageKit working.

**Unexpected behaviour you saw**

 > The PackageKit service fails with a core dump when it encounters the unknown directive `HookDir`.

```
● packagekit.service - PackageKit Daemon
   Loaded: loaded (/usr/lib/systemd/system/packagekit.service; static; vendor preset: disabled)
   Active: failed (Result: core-dump) since Thu 2019-09-26 16:52:37 -03; 2min 38s ago
  Process: 31837 ExecStart=/usr/lib/PackageKit/packagekitd (code=dumped, signal=TRAP)
 Main PID: 31837 (code=dumped, signal=TRAP)

set 26 16:52:37 erico-xps systemd[1]: Starting PackageKit Daemon...
set 26 16:52:37 erico-xps PackageKit[31837]: daemon start
set 26 16:52:37 erico-xps packagekitd[31837]: Failed to initialize alpm: using /etc/PackageKit/alpm.d/pacman.conf: /etc/PackageKit/alpm.d/pacman.conf:8/etc/pacman.conf:17unrecognised directive 'HookDir'
set 26 16:52:37 erico-xps systemd[1]: packagekit.service: Main process exited, code=dumped, status=5/TRAP
set 26 16:52:37 erico-xps systemd[1]: packagekit.service: Failed with result 'core-dump'.
set 26 16:52:37 erico-xps systemd[1]: Failed to start PackageKit Daemon.
```

**Steps to reproduce the problem**

You just need a `HookDir` directive in the `[options]` header in `/etc/pacman.conf`.

**Observation**

* This issue has been present since 2016, at least: https://bbs.archlinux.org/viewtopic.php?id=213009
* https://bugs.freedesktop.org/enter_bug.cgi?product=PackageKit doesn't allow reporting bugs for PackageKit, nor is it available on freedesktop's GitLab instance.
* I am interested in implementing the necessary fix, but I would need to know whether it's best to ignore all unknown directives or just make the `HookDir` directive "known".

**Comment by P-Daddy** [comment] 2020-05-18 16:24
:+1: I can confirm the behavior.

Since the maintainers have not responded here, perhaps the best course of action would be to go ahead and implement a fix and submit a PR.  They seem to respond pretty quickly to PRs, from what I can tell.

Not having looked at the current code, I would guess it would be fairly reasonable and safe to issue warnings for unrecognized directives and carry on.  This is, after all, what `pacman` itself does, at least in the `options` section, according to my testing.  But once you get into it, you may decide to go a different route.  Just do what makes sense and see what feedback you get on the PR.

**Comment by ericonr** [comment] 2020-05-18 20:30
@P-Daddy I'm not using Manjaro anymore, so I don't think I'm the best person to work on this rn. Feel free to take it up, if you want.

Thanks for the tips, though! They will surely help anyone who tries to deal with it.

**Comment by zany130** [comment] 2020-10-17 21:28
also have this issue on vanila arch 

OS              Arch Linux
                Kernel          5.9.0-3-tkg-pds
                CPU             AMD Ryzen 7 2700X Eight-Core Processor
                GPU             NVIDIA GP104

**Comment by Rubo3** [comment] 2021-02-02 17:28
I'm having the same issue on Arch Linux. I tried to track down the issue and I think it's caused by `pk_alpm_config_parse` at line 147 on `backends/alpm/pk-backend-alpm.c`. Commenting `HookDir` seems to make the daemon work again. @ericonr as per your third observation, I don't know what would be better to do.

**Comment by smac89** [comment] 2021-06-05 23:09
Further tracked it down to:
https://github.com/PackageKit/PackageKit/blob/74a791e2d0c2af3409b73439204c9e14937115f1/backends/alpm/pk-alpm-config.c#L602-L605

The call that should have found `HookDir` starts here:
https://github.com/PackageKit/PackageKit/blob/74a791e2d0c2af3409b73439204c9e14937115f1/backends/alpm/pk-alpm-config.c#L579-L581

I bet if someone goes into this array and adds `HookDir` to it and that struct and finally to the array, we can put this 5 year old issue to rest:
https://github.com/PackageKit/PackageKit/blob/74a791e2d0c2af3409b73439204c9e14937115f1/backends/alpm/pk-alpm-config.c#L352-L364

**Comment by smac89** [comment] 2021-06-06 05:07
Reported to arch devs:
https://bugs.archlinux.org/task/71140

**Comment by ericonr** [comment] 2021-06-07 11:25
I wonder why the patches weren't upstreamed...

**Comment by smac89** [comment] 2021-06-08 01:34
@ericonr that's a good question. At this point, their patches have made the package more like a fork than just being patched.

**Comment by smac89** [comment] 2021-06-08 01:47
@ericonr that's a good question. At this point, their patches have made the package more like a fork than just being patched.

**Comment by Macr0Nerd** [comment] 2021-07-27 06:22
Can confirm still getting this behaviour. Due to the failed startup of the daemon, startup times have significantly increased to the point where I'm more likely to uninstall the package than continue to use it.

**Comment by smac89** [comment] 2021-11-17 14:57
Looks like #487 has introduced a [fix](https://github.com/PackageKit/PackageKit/pull/487/commits/130a71e8e9803c471dd868599247004a1113751f) for the `HookDir` issue

**Comment by adrianinsaval** [comment] 2022-09-09 23:55
the PR was merged but I still experience this issue

**Comment by adrianinsaval** [comment] 2022-09-09 23:59
should this not be `alpm_option_set_hookdirs` or something?
https://github.com/PackageKit/PackageKit/blob/7e700e2177ca3f84ea5a2978cdf687179b3445a9/backends/alpm/pk-alpm-config.c#L1017

**Comment by adrianinsaval** [comment] 2022-09-10 00:06
made a PR #575 with the change but have not actually tested.

**Closed** 2022-10-12 14:56 UTC
