### ISSUE TITLE
gir and vapi files are malformed

### ISSUE THREAD

**Issue by mcatanzaro** [PackageKit/PackageKit#212] opened 2017-08-11 16:12 UTC
For some reason, the gir and vapi files generated by PackageKit-1.1.6. This issue *does not* occur when building GNOME from git modules. It only occurs when building GNOME from tarballs.

The issue results in the following simple-scan build failure:

```
[6/18] Compiling Vala source ../../../../releases/gnome-apps-3.25.90/simple-scan-3.25.90/src/config.vapi ../../../../releases/gnome-apps-3.25.90/simple-scan-3.25.90/src/app-window.vala ../../../../releases/gnome-apps-3.25.90/simple-scan-3.25.90/src/authorize-dialog.vala ../../../../releases/gnome-apps-3.25.90/simple-scan-3.25.90/src/book.vala ../../../../releases/gnome-apps-3.25.90/simple-scan-3.25.90/src/book-view.vala ../../../../releases/gnome-apps-3.25.90/simple-scan-3.25.90/src/page.vala ../../../../releases/gnome-apps-3.25.90/simple-scan-3.25.90/src/page-view.vala ../../../../releases/gnome-apps-3.25.90/simple-scan-3.25.90/src/preferences-dialog.vala ../../../../releases/gnome-apps-3.25.90/simple-scan-3.25.90/src/simple-scan.vala ../../../../releases/gnome-apps-3.25.90/simple-scan-3.25.90/src/scanner.vala ../../../../releases/gnome-apps-3.25.90/simple-scan-3.25.90/src/screensaver.vala ../../../../releases/gnome-apps-3.25.90/simple-scan-3.25.90/src/autosave-manager.vala.
FAILED: src/simple-scan@exe/app-window.c src/simple-scan@exe/authorize-dialog.c src/simple-scan@exe/book.c src/simple-scan@exe/book-view.c src/simple-scan@exe/page.c src/simple-scan@exe/page-view.c src/simple-scan@exe/preferences-dialog.c src/simple-scan@exe/simple-scan.c src/simple-scan@exe/scanner.c src/simple-scan@exe/screensaver.c src/simple-scan@exe/autosave-manager.c
valac -C --debug --pkg libwebpmux --pkg libwebp --pkg packagekit-glib2 --pkg colord --pkg sane-backends --pkg gusb --pkg gdk-pixbuf-2.0 --pkg cairo --pkg zlib --pkg gtk+-3.0 --target-glib ' 2.38' --pkg glib-2.0 -d src/simple-scan@exe --gresources=../../../../releases/gnome-apps-3.25.90/simple-scan-3.25.90/src/simple-scan.gresource.xml --pkg=posix --vapidir=/home/mcatanzaro/releases/gnome-apps-3.25.90/simple-scan-3.25.90/src -D HAVE_COLORD -D HAVE_PACKAGEKIT -D HAVE_WEBP ../../../../releases/gnome-apps-3.25.90/simple-scan-3.25.90/src/config.vapi ../../../../releases/gnome-apps-3.25.90/simple-scan-3.25.90/src/app-window.vala ../../../../releases/gnome-apps-3.25.90/simple-scan-3.25.90/src/authorize-dialog.vala ../../../../releases/gnome-apps-3.25.90/simple-scan-3.25.90/src/book.vala ../../../../releases/gnome-apps-3.25.90/simple-scan-3.25.90/src/book-view.vala ../../../../releases/gnome-apps-3.25.90/simple-scan-3.25.90/src/page.vala ../../../../releases/gnome-apps-3.25.90/simple-scan-3.25.90/src/page-view.vala ../../../../releases/gnome-apps-3.25.90/simple-scan-3.25.90/src/preferences-dialog.vala ../../../../releases/gnome-apps-3.25.90/simple-scan-3.25.90/src/simple-scan.vala ../../../../releases/gnome-apps-3.25.90/simple-scan-3.25.90/src/scanner.vala ../../../../releases/gnome-apps-3.25.90/simple-scan-3.25.90/src/screensaver.vala ../../../../releases/gnome-apps-3.25.90/simple-scan-3.25.90/src/autosave-manager.vala
../../../../releases/gnome-apps-3.25.90/simple-scan-3.25.90/src/app-window.vala:1441.95-1441.100: error: The name `code' does not exist in the context of `Pk.Error'
                       result_text = _("Failed to install drivers (error code %d).").printf (e.code);
                                                                                            ^^^^^^
Compilation failed: 1 error(s), 0 warning(s)
ninja: build stopped: subcommand failed.
```

The problem seems to be that in GNOME we have two different, competing packagekit-glib2.vapi files: one installed by PackageKit and one installed by vala. The one installed by vala has Error.code, but the one installed by PackageKit seems to take precedence, and it does not have Error.code. The two sets of bindings are really significantly/worryingly different. The vapi shipped by vala is correct and the vapi generated by PackageKit (again, when everything is built from tarball releases) is broken.

I have absolutely no clue what is wrong, so as a workaround, **GNOME will build PackageKit without Vala support until this bug is fixed**. That way simple-scan will build against the vapi provided by vala.

**Comment by hughsie** [comment] 2017-08-11 16:14
What's the long term plan for the vapi -- to be shipped by vala or the end-project?

**Comment by mcatanzaro** [comment] 2017-08-11 16:19
Vala is planning to eventually remove its PackageKit vapi in order to favor the upstream vapi (yours). Same goes for some other GNOME projects like libsoup.

Yet other GNOME projects are going the other way and removing their vala support.

**Comment by robert-ancell** [comment] 2017-08-14 02:00
Comments in other threads suggested this was broken further upstream, perhaps in the GIR generation or the glib-mkenums code. Since the .vapi is generated from the .gir I suspect whatever issue is causing this would also be breaking the .gir (e.g. Python apps).

(Un)fortunately I wasn't able to reproduce a bad .vapi generation on Ubuntu 17.10.

**Comment by hughsie** [comment] 2017-08-14 08:52
> I wasn't able to reproduce a bad .vapi generation on Ubuntu 17.10.

Nor me on Fedora 26, in the GIR I see:

      <property name="code"
                version="0.5.5"
                writable="1"
                transfer-ownership="none">
        <type name="ErrorEnum"/>
      </property>

and in the vapi:

		public Pk.ErrorEnum code { get; set; }

**Comment by mcatanzaro** [comment] 2017-08-14 14:16
The gir is only broken when building GNOME from tarball releases, not from git. I'll try to generate it again.

**Comment by mcatanzaro** [comment] 2017-08-14 14:29
And I no longer think it's related to glib-mkenums, but it is very suspicious that all the differences in the gir file are enum-related. (Still need to generate it again to post here.)

**Comment by mcatanzaro** [comment] 2017-08-14 14:56
To reproduce, use the official GNOME 3.25.90 JHBuild modulesets:

https://download.gnome.org/teams/releng/3.25.90/

Edit line 1120 of gnome-suites-core-3.25.90.modules and change `--disable-vala` to `--enable-vala`. Then run:

`$ jhbuild -f sample-tarball.jhbuildrc -m gnome-apps-3.25.90.modules build PackageKit`

And fish the broken files out of either your build directory or the install tree. Unfortunately GitHub apparently does not allow attaching arbitrary files and it has a comment length limit, so that prevents me from adding the contents of the broken gir and vapi files to this bug report. And I will avoid uploading them to a pastebin since it's very annoying to find broken links in bug reports. Do you still use freedesktop Bugzilla? There is still a PackageKit component there where we could attach files.

**Comment by mcatanzaro** [comment] 2017-08-14 15:01
Carlos Soriano suggested I use gist. It works:

The gir: https://gist.github.com/mcatanzaro/27912fbbcb9f2f41bec9b07e09f944a3
The vapi: https://gist.github.com/mcatanzaro/af80d81a0189c425e87685cdbbf6978f

Note: you **must** build from tarballs to reproduce. The bug does not occur when everything is built from git.

**Comment by ximion** [comment] 2022-02-16 21:58
I assume this is fixed now with the Meson migration, please feel free to reopen this issue if the bug is still there!

**Closed by ximion** 2022-02-16 21:58 UTC
