### ISSUE TITLE
[dnf backend] Not in sync

### ISSUE THREAD

**Issue by Justinzobel** [PackageKit/PackageKit#542] opened 2022-04-16 00:15 UTC
```
pkcon update
Getting updates               [=========================]         
Finished                      [=========================]         
Starting                      [=========================]         
Testing changes               [=========================]         
Finished                      [                         ] (0%)  
The following packages have to be updated:
 nspr-4.32.0-6.fc36.i686        Netscape Portable Runtime
 nspr-4.32.0-6.fc36.x86_64      Netscape Portable Runtime
Proceed with changes? [N/y]
```

```
dnf update --refresh
Copr repo for plasma-mobile-apps owned by justinz                                      2.8 kB/s | 3.6 kB     00:01    
Fedora 36 - x86_64                                                                      16 kB/s |  17 kB     00:01    
Fedora 36 openh264 (From Cisco) - x86_64                                               1.3 kB/s | 989  B     00:00    
Fedora Modular 36 - x86_64                                                              29 kB/s |  31 kB     00:01    
Fedora 36 - x86_64 - Updates                                                           5.0 kB/s | 3.4 kB     00:00    
Fedora Modular 36 - x86_64 - Updates                                                   4.2 kB/s | 3.4 kB     00:00    
google-chrome                                                                          5.1 kB/s | 1.3 kB     00:00    
RPM Fusion for Fedora 36 - Free                                                        7.1 kB/s | 5.3 kB     00:00    
RPM Fusion for Fedora 36 - Free - Test Updates                                         6.7 kB/s | 5.1 kB     00:00    
RPM Fusion for Fedora 36 - Nonfree                                                     7.2 kB/s | 5.4 kB     00:00    
RPM Fusion for Fedora 36 - Nonfree - Test Updates                                      6.8 kB/s | 5.2 kB     00:00    
Dependencies resolved.
=======================================================================================================================
 Package                                 Architecture         Version                       Repository            Size
=======================================================================================================================
Upgrading:
 anaconda                                x86_64               36.16.5-1.fc36                fedora               111 k
 anaconda-core                           x86_64               36.16.5-1.fc36                fedora               2.3 M
 anaconda-gui                            x86_64               36.16.5-1.fc36                fedora               465 k
 anaconda-install-env-deps               x86_64               36.16.5-1.fc36                fedora               111 k
 anaconda-live                           x86_64               36.16.5-1.fc36                fedora               122 k
 anaconda-tui                            x86_64               36.16.5-1.fc36                fedora               203 k
 anaconda-widgets                        x86_64               36.16.5-1.fc36                fedora               144 k
 flatpak                                 x86_64               1.12.7-2.fc36                 fedora               1.6 M
 flatpak-devel                           x86_64               1.12.7-2.fc36                 fedora               109 k
 flatpak-libs                            x86_64               1.12.7-2.fc36                 fedora               403 k
 flatpak-selinux                         noarch               1.12.7-2.fc36                 fedora                22 k
 flatpak-session-helper                  x86_64               1.12.7-2.fc36                 fedora                44 k
 gjs                                     x86_64               1.72.0-2.fc36                 fedora               486 k
 kf5-kirigami2                           x86_64               5.91.0-3.fc36                 fedora               432 k
 kf5-kirigami2-devel                     x86_64               5.91.0-3.fc36                 fedora                53 k
 mozjs91                                 x86_64               91.8.0-1.fc36                 fedora               4.3 M
 nspr                                    i686                 4.32.0-6.fc36                 fedora               149 k
 nspr                                    x86_64               4.32.0-6.fc36                 fedora               137 k
 selinux-policy                          noarch               36.6-1.fc36                   fedora                71 k
 selinux-policy-targeted                 noarch               36.6-1.fc36                   fedora               6.3 M
 xdg-desktop-portal-gnome                x86_64               42.0.1-4.fc36                 fedora               181 k
 xdg-desktop-portal-gtk                  x86_64               1.12.0-5.fc36                 fedora               131 k

Transaction Summary
=======================================================================================================================
Upgrade  22 Packages

Total size: 18 M
Total download size: 17 M
Is this ok [y/N]:
```

**Comment by Justinzobel** [comment] 2022-04-16 00:15
@Conan-Kudo

**Comment by Conan-Kudo** [comment] 2022-04-16 05:36
Duplicate of #338

**Closed by Conan-Kudo** 2022-04-16 05:36 UTC
Labels: Backend: dnf (Fedora Linux)

**Comment by Justinzobel** [comment] 2022-04-16 10:05
How is the linked issue related? The issue here is dnf and pkcon not
showing the same issues. Not cache related

**Comment by Justinzobel** [comment] 2022-04-17 01:20
@Conan-Kudo I don't believe this issue is a duplicate.
